[versions]
dynatest = "0.24"
slf4j = "2.0.11"
kaributools = "0.19"
karibudsl = "2.1.2"
junit5 = "5.9.3"
# Check the newest Vaadin version at https://github.com/vaadin/platform/tags
vaadin24 = "24.3.3"
vaadin24_spring = "24.3.3"
vaadin24next = "24.4.0.alpha2"
vaadin24next_spring = "24.4.0.alpha2"

[libraries]
dynatest = { module = "com.github.mvysny.dynatest:dynatest", version.ref = "dynatest" }
slf4j-api = { module = "org.slf4j:slf4j-api", version.ref = "slf4j" }
slf4j-simple = { module = "org.slf4j:slf4j-simple", version.ref = "slf4j" }
jakarta-servlet = "jakarta.servlet:jakarta.servlet-api:5.0.0"
kaributools = { module = "com.github.mvysny.karibu-tools:karibu-tools", version.ref = "kaributools" }
kaributools23 = { module = "com.github.mvysny.karibu-tools:karibu-tools-23", version.ref = "kaributools" }
karibudsl = { module = "com.github.mvysny.karibudsl:karibu-dsl", version.ref = "karibudsl" }
karibudsl23 = { module = "com.github.mvysny.karibudsl:karibu-dsl-v23", version.ref = "karibudsl" }
junit-jupiterapi = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junit5" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit5" }
vaadin24 = { module = "com.vaadin:vaadin", version.ref = "vaadin24" }
vaadincore24 = { module = "com.vaadin:vaadin-core", version.ref = "vaadin24" }
vaadinspring24 = { module = "com.vaadin:vaadin-spring", version.ref = "vaadin24_spring" }
vaadin24next = { module = "com.vaadin:vaadin", version.ref = "vaadin24next" }
vaadincore24next = { module = "com.vaadin:vaadin-core", version.ref = "vaadin24next" }
vaadinspring24next = { module = "com.vaadin:vaadin-spring", version.ref = "vaadin24next_spring" }
