[versions]
dynatest = "0.24"
slf4j = "2.0.9"
kaributools = "0.19"
karibudsl = "2.1.2"
junit5 = "5.9.3"

[libraries]
dynatest = { module = "com.github.mvysny.dynatest:dynatest", version.ref = "dynatest" }
slf4j-api = { module = "org.slf4j:slf4j-api", version.ref = "slf4j" }
slf4j-simple = { module = "org.slf4j:slf4j-simple", version.ref = "slf4j" }
jakarta-servlet = "jakarta.servlet:jakarta.servlet-api:5.0.0"
kaributools = { module = "com.github.mvysny.karibu-tools:karibu-tools", version.ref = "kaributools" }
kaributools23 = { module = "com.github.mvysny.karibu-tools:karibu-tools-23", version.ref = "kaributools" }
karibudsl = { module = "com.github.mvysny.karibudsl:karibu-dsl", version.ref = "karibudsl" }
karibudsl23 = { module = "com.github.mvysny.karibudsl:karibu-dsl-v23", version.ref = "karibudsl" }
junit-jupiterapi = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junit5" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit5" }
