[versions]
dynatest = "0.24"
slf4j = "2.0.9"

[libraries]
dynatest = { module = "com.github.mvysny.dynatest:dynatest", version.ref = "dynatest" }
slf4j-api = { module = "org.slf4j:slf4j-api", version.ref = "slf4j" }
slf4j-simple = { module = "org.slf4j:slf4j-simple", version.ref = "slf4j" }
jakarta-servlet = "jakarta.servlet:jakarta.servlet-api:5.0.0"
